[tool.black]
line-length = 150

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "podonos"
version = "0.48.0"
description = "Managed evaluation for audio & speech"
readme = "README.md"
license = "MIT"
authors = [
    {name = "David Anderson", email = "david@podonos.com"}
]
requires-python = ">=3.10"
dependencies = [
    "filetype",
    "glog",
    "natsort",
    "packaging",
    "requests>=2.33.0,<3",
    "urllib3>=2.7.0,<3",
    "soundfile==0.12.1",
    "tqdm",
    "typing_extensions>=4.0.0"
]
keywords = ["ai", "speech", "synthesis"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

[project.optional-dependencies]
dev = [
    "numpy>=2.0.0,<2.4.0; python_version < '3.14'",
    "numpy>=2.4.0; python_version >= '3.14'",
    "pytest",
]

[project.urls]
Homepage="https://www.podonos.com"
Repository="https://github.com/podonos/podonos-pysdk"

[tool.setuptools.packages.find]
include = ["podonos*"]
exclude = ["aws*", "openai*", "output*", "tests*"]
